### ISSUE TITLE
Diaspora ID validation rule validates hostnames with the underscore character

### ISSUE THREAD

**Issue by cmrd-senya** [SuperTux88/diaspora_federation#33]
Hey!

[The validation rule](https://github.com/SuperTux88/diaspora_federation/blob/develop/lib/diaspora_federation/validators/rules/diaspora_id.rb) validates "ilya_123@join_diaspora.com" diaspora ID as correct. I picked that example from the diaspora test suite, and it is expected to be incorrect [there](https://github.com/diaspora/diaspora/blob/develop/spec/controllers/people_controller_spec.rb#L533). I searched the web, and it is stated everywhere, that underscores in the hostnames aren't allowed: https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names.

**Comment by SuperTux88** [comment]
I changed and simplified the regex a bit, so it doesn't allow hostnames with underscores now. But it still doesn't catch all invalid hostnames, because I don't want to maintain a complex regex for this and it is also more error prone. A complex regex doesn't help us much here, only for some edge-cases that probably don't even exist, because nobody can register an invalid domain.

**Comment by cmrd-senya** [comment]
Thanks! I wonder whether there is any ready-made publicly known regexp for domain. It looks like a common task, so maybe it can be found anywhere. I would say I would expect something like this to be in some official documents.
